project: https://platform.activestate.com/nathanr/Python3?commitID=623dadf8-ebf9-4876-bfde-f45afafe5ea8
constants:
  - name: PLACE
    value: WORLD
jobs:
  - name: build
    constants:
      - PLACE
    scripts:
      - assert
      - hello
scripts:
  - name: assert
    language: bash
    value: |
      echo $PATH
      which state
      which python3
  - name: hello
    language: bash
    value: echo Hello $PLACE