name: State Tool Generated Workflow
"on":
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    env:
      PLACE: WORLD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install State Tool
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n -f
    - name: assert
      run: state run assert
    - name: hello
      run: state run hello

